services:
  - type: web
    name: plm-server
    env: node
    rootDir: server
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: SCHEMA_REGISTRY_URL
        sync: false

  - type: web
    name: plm-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: plm-server
          property: url
